### ISSUE TITLE
Jitsi Meet with ejabberd: authentication required

### ISSUE THREAD

**Issue by rasos** [jitsi/jitsi-meet#1306]
As ejabberd is already running on our server and to avoid port conflicts we want to replace Prosody with ejabberd. We followed this tutorial: https://jitsi.org/Projects/JitsiVideobridgeWithEjabberd

We have two issues: 
1. After entering the conference room an additional xmpp login is needed. If I enter an xmpp user's login, I can proceed. We have not found out whether ejabberd can be configured to accept anonymous users in the docs: https://docs.ejabberd.im/admin/configuration/#authentication

2. Jicofo is connecting, but cannot establish a conference
```
Jicofo 2017-02-07 10:56:12.026 INFO: [15] org.jitsi.jicofo.FocusManager.log() XMPP provider reg state: RegistrationState=Registered
Jicofo 2017-02-07 10:56:12.026 INFO: [15] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.log() XMPP provider Jabber:focus@auth.meet.domain.tld/focus360826710359579@focus.meet.domain.tld connected (JID: focus@auth.meet.domain.tld/focus360826710359579)
Jicofo 2017-02-07 11:46:05.849 SEVERE: [30] org.jitsi.meet.ComponentMain.call().278 not-authorized, host:meet.domain.tld, port:5347
org.xmpp.component.ComponentException: not-authorized
```
We had adapted the following lines in /opt/ejabberd-16.04/conf/ejabberd.yml:
```
hosts:
  - "conference.meet.domain.tld"
  - "jitsi-videobridge.meet.domain.tld"

additional section:
-
    port: 5347
    module: ejabberd_service
    access: all
    shaper_rule: fast
    ip: "127.0.0.1"
    hosts:
      "jitsi-videobridge.meet.domain.tld":
         password: "1234#5"
```
Anybody running Jitsi meet with ejabberd?
