### ISSUE TITLE
Ability to hide dominant speaker square in 1-on-1 calls

### ISSUE THREAD

**Issue by jgarplind** [jitsi/jitsi-meet#13953]
**Is your feature request related to a problem you are facing?**
We wish to create a stripped down UI to allow technically impaired users to be able to have a 1-on-1 video conversation without being confused by superfluous visual elements/controls.

**Describe the solution you'd like**
I opened a [thread on the forums](https://community.jitsi.org/t/hide-non-self-view-part-of-filmstrip-during-1-on-1/127522), but I believe the interest has been low due to the inability to do what we want to do with current configuration options. I would like any way to create a more focussed experience, removing "advanced" elements and interactions.

![image](https://github.com/jitsi/jitsi-meet/assets/10069144/20d8db82-437b-4386-9e0e-4a6fc245dbe5)

**Describe alternatives you've considered**
I've looked into:
- existing config options:
  - `remoteVideoMenu` (would have loved `remoteVideo` instead)
  - toolbarOptions (to auto-hide sooner, doesn't seem to make a difference)
  -  ... but none apply to this use case?
- doing a CSS patch (should work, but some concerns about maintainability)
- ... maybe something else?

**Comment by saghul** [comment]
I'd say a config option would be acceptable, if you are up for it.

Additionally, we can have a conversation about disabling it altogether for 1 to 1 calls, since it doesn't add much...

**Comment by jgarplind** [comment]
> Additionally, we can have a conversation about disabling it altogether for 1 to 1 calls, since it doesn't add much...

This would be ideal in my opinion, but I'm not sure what kind of work that would entail.

> if you are up for it.

Sure! But it doesn depend on the magnitude. It is a nuissance for us, but we are a small company and we can't currently prioritize dedicating week(s) on minor nuissances.

**Comment by saghul** [comment]
Good news, we have that already in place! https://github.com/jitsi/jitsi-meet/blob/d02c7dc3a713ac79d786189c27d3ce66392af6a4/interface_config.js set that to `true` and you're good to go!

**Comment by jgarplind** [comment]
> Good news, we have that already in place! https://github.com/jitsi/jitsi-meet/blob/d02c7dc3a713ac79d786189c27d3ce66392af6a4/interface_config.js set that to `true` and you're good to go!

Oh wow, great news indeed.

Sorry, but I think you didn't manage to link to a specific line. Can you specify the property? :)

**Comment by saghul** [comment]
Ops! https://github.com/jitsi/jitsi-meet/blob/d02c7dc3a713ac79d786189c27d3ce66392af6a4/interface_config.js#L32

**Comment by jgarplind** [comment]
Ah!

I've seen that, and _I think_, it only applies to the "badge" right above the toolbar?

Can confirm once more if you think otherwise.

**Comment by saghul** [comment]
No, it should also apply to the blue border.

**Comment by jgarplind** [comment]
> it should also apply to the blue border

Ah. I should have been more explicit. This works indeed, but is not exactly what I'm looking for.

I don't mind the blue border so much (although it is a slight improvement that it is gone), rather, _I would like to remove that whole square_, so essentially anything in the filmstrip that is not my self-view is in my interest to hide.

By default, we will see the self-view, and a list of "remote-videos", which in the 1-on-1 context only has 1 item: the "dominant speaker square", if you will.

In the 1-on-1 scenario, I don't see any use for the "remote-videos" UI at all, so _that_ is what I would be very grateful if I was able to hide.

**Comment by jgarplind** [comment]
@saghul For now, I've ended up with a CSS workaround, documented like so:

### Adjusting CSS

In `/usr/share/jitsi-meet/index.html`, add a link to a custom css file:

```diff
    <!--#include virtual="fonts.html"-->
+   <link rel="stylesheet" href="css/custom.css">
    <link rel="manifest" id="manifest-placeholder">
```

In `usr/share/jitsi-meet/css/custom.css`, add custom css:

```css
/* Depending on screen size, one of these represents the superfluous blackish square showing the other party again. */
:not(#localVideoContainer).videocontainer.display-video {
        display: none !important;
}

.filmstrip .remote-videos.is-not-overflowing>div{
        display:none !important;
}

/* `mobile-browser` class is appended when Jitsi detects a mobile browser.
 * In mobile, we don't want to allow pointer-events, to avoid misclicks, which could lead to strange UI, e.g. focussing on self-view.
 * The hang-up button (and the rest of the toolbar) is not impacted by this.
 */
body.mobile-browser {
        pointer-events: none !important;
}
```

Do you have any input on whether this could be:
1. Further improved CSS-wise? (I've seen a black box or two flickering by still)
2. Somehow implemented as a config option?
