### ISSUE TITLE
conference.videobridgeNotAvailable – All Room partitipants disconnected on initial connection

### ISSUE THREAD

**Issue by chris-aeviator** [jitsi/jitsi-meet#4302]
## Description
---
I'm self-hosting jitsi-meet with the provided docker container. I was able to get a perfectly running 30 min call with my companies partner the first time we tried it (different network, 5 km away from each other, each having a 50mb+ connection). However, all following calls "crash" as soon as a second person comes into the room (besides the owner). 

## Current behavior
---
When starting a call as the owner (creating the room) the call instantly crashes for all partitipants (in sync) when the second person joins the room. The 15 second reconnect starts and as soon as both partitipants are back it crashes again, and so on.

Log:

```jicofo_1   | Jicofo 2019-06-05 13:26:14.396 INFO: [38] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Granted owner to nidomeetsmyzel@muc.meet.jitsi/n4cexk9o
jicofo_1   | Jicofo 2019-06-05 13:26:14.397 INFO: [38] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member nidomeetsmyzel@muc.meet.jitsi/n4cexk9o joined.
web_1      | 172.19.0.20 - - [05/Jun/2019:13:26:15 +0200] "POST /http-bind?room=nidomeetsmyzel HTTP/1.1" 200 1764 "https://meet.oi.myzel.io/nidoMeetsMyzel" "Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0"
jvb_1      | JVB 2019-06-05 13:26:17.207 INFO: [19] org.jitsi.videobridge.VideobridgeExpireThread.log() Running expire()
web_1      | 172.19.0.20 - - [05/Jun/2019:13:26:18 +0200] "GET /config.js?room=nidomeetsmyzel HTTP/1.1" 200 14257 "-" "okhttp/3.6.0"
prosody_1  | bosh3ae514b4-a2cd-4030-8b62-13913c4794b2  info     BOSH client disconnected: session close
web_1      | 172.19.0.20 - - [05/Jun/2019:13:26:18 +0200] "POST /http-bind?room=nidomeetsmyzel HTTP/1.1" 200 261 "-" "okhttp/3.6.0"
web_1      | 172.19.0.20 - - [05/Jun/2019:13:26:18 +0200] "POST /http-bind?room=nidomeetsmyzel HTTP/1.1" 200 116 "-" "okhttp/3.6.0"
prosody_1  | mod_bosh                                  info     New BOSH session, assigned it sid '0d60ac83-3f6a-4550-9faa-7e3b78132308'
web_1      | 172.19.0.20 - - [05/Jun/2019:13:26:18 +0200] "POST /http-bind?room=nidomeetsmyzel HTTP/1.1" 200 498 "-" "okhttp/3.6.0"
prosody_1  | bosh0d60ac83-3f6a-4550-9faa-7e3b78132308  info     Authenticated as vlypv0hi9qurinul@meet.jitsi
web_1      | 172.19.0.20 - - [05/Jun/2019:13:26:18 +0200] "POST /http-bind?room=nidomeetsmyzel HTTP/1.1" 200 199 "-" "okhttp/3.6.0"
web_1      | 172.19.0.20 - - [05/Jun/2019:13:26:18 +0200] "POST /http-bind?room=nidomeetsmyzel HTTP/1.1" 200 503 "-" "okhttp/3.6.0"
web_1      | 172.19.0.20 - - [05/Jun/2019:13:26:19 +0200] "POST /http-bind?room=nidomeetsmyzel HTTP/1.1" 200 312 "-" "okhttp/3.6.0"
web_1      | 172.19.0.20 - - [05/Jun/2019:13:26:19 +0200] "POST /http-bind?room=nidomeetsmyzel HTTP/1.1" 200 252 "-" "okhttp/3.6.0"
jvb_1      | JVB 2019-06-05 13:26:19.329 INFO: [16] org.jitsi.xmpp.mucclient.MucClientManager.log() Setting a presence extension: net.java.sip.communicator.impl.protocol.jabber.extensions.colibri.ColibriStatsExtension@7903d94
web_1      | 172.19.0.20 - - [05/Jun/2019:13:26:19 +0200] "POST /http-bind?room=nidomeetsmyzel HTTP/1.1" 200 2632 "-" "okhttp/3.6.0"
jicofo_1   | Jicofo 2019-06-05 13:26:19.465 INFO: [80] org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq().402 Focus request for room: nidomeetsmyzel@muc.meet.jitsi
web_1      | 172.19.0.20 - - [05/Jun/2019:13:26:19 +0200] "POST /http-bind?room=nidomeetsmyzel HTTP/1.1" 200 552 "-" "okhttp/3.6.0"
web_1      | 172.19.0.20 - - [05/Jun/2019:13:26:19 +0200] "POST /http-bind?room=nidomeetsmyzel HTTP/1.1" 200 964 "https://meet.oi.myzel.io/nidoMeetsMyzel" "Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0"
web_1      | 172.19.0.20 - - [05/Jun/2019:13:26:19 +0200] "POST /http-bind?room=nidomeetsmyzel HTTP/1.1" 200 2720 "-" "okhttp/3.6.0"
jicofo_1   | Jicofo 2019-06-05 13:26:19.686 INFO: [38] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberJoined sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@56d34ff9 member=ChatMember[nidomeetsmyzel@muc.meet.jitsi/vlypv0hi, jid: null]@1660804346]
jicofo_1   | Jicofo 2019-06-05 13:26:19.686 INFO: [38] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member nidomeetsmyzel@muc.meet.jitsi/vlypv0hi joined.
jicofo_1   | Jicofo 2019-06-05 13:26:19.686 SEVERE: [38] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Can not invite participant -- no bridge available.
jicofo_1   | Jicofo 2019-06-05 13:26:19.686 SEVERE: [38] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Can not invite participant -- no bridge available.
web_1      | 172.19.0.20 - - [05/Jun/2019:13:26:19 +0200] "POST /http-bind?room=nidomeetsmyzel HTTP/1.1" 200 1064 "https://meet.oi.myzel.io/nidoMeetsMyzel" "Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0"
web_1      | 172.19.0.20 - - [05/Jun/2019:13:26:19 +0200] "POST /http-bind?room=nidomeetsmyzel HTTP/1.1" 200 1834 "-" "okhttp/3.6.0"
web_1      | 172.19.0.20 - - [05/Jun/2019:13:26:20 +0200] "POST /http-bind?room=nidomeetsmyzel HTTP/1.1" 200 533 "https://meet.oi.myzel.io/nidoMeetsMyzel" "Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0"
jicofo_1   | Jicofo 2019-06-05 13:26:20.196 INFO: [38] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberLeft sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@56d34ff9 member=ChatMember[nidomeetsmyzel@muc.meet.jitsi/n4cexk9o, jid: n4cexk9opev_zxq7@meet.jitsi/Glsrelen]@134130037]
jicofo_1   | Jicofo 2019-06-05 13:26:20.196 INFO: [38] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Owner has left the room !
web_1      | 172.19.0.20 - - [05/Jun/2019:13:26:20 +0200] "POST /http-bind?room=nidomeetsmyzel HTTP/1.1" 200 451 "https://meet.oi.myzel.io/nidoMeetsMyzel" "Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0"
jicofo_1   | Jicofo 2019-06-05 13:26:20.199 INFO: [38] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Granted owner to nidomeetsmyzel@muc.meet.jitsi/vlypv0hi
jicofo_1   | Jicofo 2019-06-05 13:26:20.200 INFO: [38] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member nidomeetsmyzel@muc.meet.jitsi/n4cexk9o is leaving
jicofo_1   | Jicofo 2019-06-05 13:26:20.200 INFO: [38] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Removed participant: true, nidomeetsmyzel@muc.meet.jitsi/n4cexk9o
web_1      | 172.19.0.20 - - [05/Jun/2019:13:26:20 +0200] "POST /http-bind?room=nidomeetsmyzel HTTP/1.1" 200 2209 "-" "okhttp/3.6.0"
web_1      | 172.19.0.20 - - [05/Jun/2019:13:26:20 +0200] "POST /http-bind?room=nidomeetsmyzel HTTP/1.1" 200 451 "-" "okhttp/3.6.0"
jicofo_1   | Jicofo 2019-06-05 13:26:20.243 INFO: [38] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberLeft sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@56d34ff9 member=ChatMember[nidomeetsmyzel@muc.meet.jitsi/vlypv0hi, jid: vlypv0hi9qurinul@meet.jitsi/0DLu4QFp]@1660804346]
jicofo_1   | Jicofo 2019-06-05 13:26:20.243 INFO: [38] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Owner has left the room !
jicofo_1   | Jicofo 2019-06-05 13:26:20.243 INFO: [38] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member nidomeetsmyzel@muc.meet.jitsi/vlypv0hi is leaving
jicofo_1   | Jicofo 2019-06-05 13:26:20.243 INFO: [38] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Removed participant: true, nidomeetsmyzel@muc.meet.jitsi/vlypv0hi
jicofo_1   | Jicofo 2019-06-05 13:26:20.245 INFO: [38] org.jitsi.jicofo.FocusManager.log() Disposed conference for room: nidomeetsmyzel@muc.meet.jitsi conference count: 0
web_1      | 172.19.0.20 - - [05/Jun/2019:13:26:20 +0200] "POST /http-bind?room=nidomeetsmyzel HTTP/1.1" 200 508 "https://meet.oi.myzel.io/nidoMeetsMyzel" "Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0"
prosody_1  | boshfb083a43-d1d1-4da8-980c-651708989c43  info     BOSH client disconnected: session close
web_1      | 172.19.0.20 - - [05/Jun/2019:13:26:20 +0200] "POST /http-bind?room=nidomeetsmyzel HTTP/1.1" 200 261 "https://meet.oi.myzel.io/nidoMeetsMyzel" "Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0"
web_1      | 172.19.0.20 - - [05/Jun/2019:13:26:20 +0200] "POST /http-bind?room=nidomeetsmyzel HTTP/1.1" 200 868 "-" "okhttp/3.6.0"
jvb_1      | JVB 2019-06-05 13:26:21.026 INFO: [20] org.jitsi.videobridge.Videobridge.log() CAT=stat create_conf,conf_id=99d392c2b834ddda conf_name=null,logging=false,conf_count=1,ch_count=0,v_streams=0
jvb_1      | JVB 2019-06-05 13:26:21.042 INFO: [20] org.jitsi.videobridge.health.Health.log() Performed a successful health check in 16ms. Sticky failure: false


```
## Expected Behavior
---
The call should not crash upon join of another user
## Possible Solution
---

## Steps to reproduce
---
feel free to test on meet.oi.myzel.io

# Environment details
---
Docker v 18.06, Ubuntu 16.04

docker-compose.yml
```
version: '3'

services:
    # Frontend
    web:
        image: jitsi/web
        ports:
            - '80'
            - '443'
        volumes:
            - ${CONFIG}/web:/config
        environment:
            - ENABLE_AUTH
            - ENABLE_GUESTS
            - ENABLE_LETSENCRYPT
            - ENABLE_HTTP_REDIRECT
            - DISABLE_HTTPS
            - JICOFO_AUTH_USER
            - LETSENCRYPT_DOMAIN
            - LETSENCRYPT_EMAIL
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_BOSH_URL_BASE=http://xmpp.meet.jitsi:5280
            - XMPP_GUEST_DOMAIN
            - XMPP_MUC_DOMAIN
            - TZ
        labels:
          - 'traefik.docker.network=traefik'
          - 'traefik.backend=web'
          - 'traefik.port=80'
          - 'traefik.frontend.rule=Host:meet.oi.myzel.io'
        networks:
            - traefik
            - meet.jitsi

    # XMPP server
    prosody:
        image: jitsi/prosody
        expose:
            - '5222'
            - '5347'
            - '5280'
        volumes:
            - ${CONFIG}/prosody:/config
        environment:
            - ENABLE_AUTH
            - ENABLE_GUESTS
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_GUEST_DOMAIN
            - XMPP_MUC_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_MODULES
            - XMPP_MUC_MODULES
            - XMPP_INTERNAL_MUC_MODULES
            - JICOFO_COMPONENT_SECRET
            - JICOFO_AUTH_USER
            - JICOFO_AUTH_PASSWORD
            - JVB_AUTH_USER
            - JVB_AUTH_PASSWORD
            - JIGASI_XMPP_USER
            - JIGASI_XMPP_PASSWORD
            - TZ
        networks:
            meet.jitsi:
                aliases:
                    - xmpp.meet.jitsi
   # Focus component
    jicofo:
        image: jitsi/jicofo
        volumes:
            - ${CONFIG}/jicofo:/config
        environment:
            - ENABLE_AUTH
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_SERVER=xmpp.meet.jitsi
            - JICOFO_COMPONENT_SECRET
            - JICOFO_AUTH_USER
            - JICOFO_AUTH_PASSWORD
            - JVB_BREWERY_MUC
            - JIGASI_BREWERY_MUC
            - TZ
        depends_on:
            - prosody
        networks:
            meet.jitsi:

    # Video bridge
    jvb:
        image: jitsi/jvb
        ports:
            - '${JVB_PORT}:${JVB_PORT}/udp'
            - '${JVB_TCP_PORT}:${JVB_TCP_PORT}'
        volumes:
            - ${CONFIG}/jvb:/config
        environment:
            - DOCKER_HOST_ADDRESS
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_SERVER=xmpp.meet.jitsi
            - JVB_AUTH_USER
            - JVB_AUTH_PASSWORD
            - JVB_BREWERY_MUC
            - JVB_PORT
            - JVB_TCP_HARVESTER_DISABLED
            - JVB_TCP_PORT
            - JVB_STUN_SERVERS
            - JVB_ENABLE_APIS
            - JICOFO_AUTH_USER
            - TZ
        depends_on:
            - prosody
        networks:
            meet.jitsi:

# Custom network so all services can communicate using a FQDN
networks:
    meet.jitsi:
    traefik:
      external: true


```

EDIT:

Output from the browser's JS console

```[modules/xmpp/xmpp.js] <value>:  (TIME) Strophe disconnecting:	 21786 Logger.js:124:12
[modules/xmpp/xmpp.js] <value>:  (TIME) Strophe disconnected:	 21786 Logger.js:124:12
InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
(TIME) index.html loaded:	 567 nidoMeetsMyzel:18:9
[modules/browser/BrowserCapabilities.js] <t>:  This appears to be firefox, ver: 66.0 Logger.js:124:12
[react/index.web.js] <>:  (TIME) document ready:	 1779 Logger.js:124
[react/features/base/storage/PersistenceRegistry.js] <value>:  redux state rehydrated as 
Object { "features/base/settings": {…}, "features/dropbox": {}, "features/recent-list": (3) […], "features/welcome": {}, "features/video-layout": {}, "features/base/known-domains": (3) […] }
Logger.js:124
[modules/UI/videolayout/VideoLayout.js] <changeUserAvatar>:  Missed avatar update - no small video yet for undefined Logger.js:124
[JitsiMeetJS.js] <init>:  Analytics disabled, disposing. Logger.js:124:12
[modules/statistics/AnalyticsAdapter.js] <value>:  Disposing of analytics adapter. Logger.js:124:12
[react/features/base/media/middleware.js] <>:  Start muted: Logger.js:124
[react/features/base/media/middleware.js] <>:  Start audio only set to false Logger.js:124
[react/features/base/conference/middleware.js] <>:  Audio-only disabled Logger.js:124
[modules/RTC/RTCUtils.js] <value>:  Using the new gUM flow Logger.js:124:12
[modules/xmpp/xmpp.js] <value>:  P2P STUN servers:  
Array(3) [ {…}, {…}, {…} ]
Logger.js:124:12
[modules/xmpp/xmpp.js] <value>:  (TIME) Strophe connecting:	 2385 Logger.js:124:12
[modules/RTC/RTCUtils.js] <value/i<>:  Got media constraints:  
Object { video: {…}, audio: {…} }
Logger.js:124:12
[modules/RTC/RTCUtils.js] <value/<>:  Available devices:  
Array(6) [ MediaDeviceInfo, MediaDeviceInfo, MediaDeviceInfo, MediaDeviceInfo, MediaDeviceInfo, MediaDeviceInfo ]
Logger.js:124:12
[modules/xmpp/xmpp.js] <value>:  (TIME) Strophe connected:	 3453 Logger.js:124:12
[modules/xmpp/xmpp.js] <value>:  My Jabber ID: reznsoa8hj8fbccy@meet.jitsi/Z5Wwt3gZ Logger.js:124:12
[modules/xmpp/strophe.ping.js] <value>:  XMPP pings will be sent every 10000 ms Logger.js:124:12
[react/features/base/storage/PersistenceRegistry.js] <value>:  redux state persisted. eb9bd64a8101af7c5a1daee32f6b2a39 -> 5ecdfc461e7fe6e3859fb8c0f10ffd84 Logger.js:124
[modules/RTC/RTCUtils.js] <value/</<>:  onUserMediaSuccess Logger.js:124:12
[modules/RTC/JitsiLocalTrack.js] <value>:  Setting new MSID: {2f31d8fc-5cdc-412f-8a1b-04ddd351258c} {b0b24056-34ca-4e94-834c-af3d66e6e71b} on LocalTrack[undefined,audio] Logger.js:124:12
[modules/RTC/JitsiLocalTrack.js] <value>:  Setting new MSID: {df38cece-f957-43ea-b0df-b642ec985bda} {7f7ef518-4d4b-4591-9f60-5582d2afc65b} on LocalTrack[undefined,video] Logger.js:124:12
[conference.js] <init/<>:  initialized with 2 local tracks Logger.js:124
[modules/xmpp/ChatRoom.js] <t>:  Joined MUC as nidomeetsmyzel@muc.meet.jitsi/reznsoa8 Logger.js:124:12
[modules/e2eping/e2eping.js] <e>:  Initializing e2e ping; pingInterval=10000, analyticsInterval=60000. Logger.js:124:12
[modules/connectivity/ParticipantConnectionStatus.js] <e>:  RtcMuteTimeout set to: 2000 Logger.js:124:12
[modules/statistics/AvgRTPStatsReporter.js] <e>:  Avg RTP stats will be calculated every 15 samples Logger.js:124:12
[JitsiConference.js] <X>:  backToP2PDelay: 5 Logger.js:124:12
[modules/videosipgw/VideoSIPGW.js] <e>:  creating VideoSIPGW Logger.js:124:12
[modules/UI/videolayout/VideoLayout.js] <electLastVisibleVideo>:  Last visible video no longer exists Logger.js:124
[modules/UI/videolayout/VideoLayout.js] <electLastVisibleVideo>:  Fallback to local video... Logger.js:124
[modules/UI/videolayout/VideoLayout.js] <electLastVisibleVideo>:  electLastVisibleVideo: reznsoa8 Logger.js:124
[JitsiConference.js] <X.prototype._doReplaceTrack>:  _doReplaceTrack - no JVB JingleSession Logger.js:124:12
[JitsiConference.js] <X.prototype._doReplaceTrack>:  _doReplaceTrack - no P2P JingleSession Logger.js:124:12
[JitsiConference.js] <X.prototype._doReplaceTrack>:  _doReplaceTrack - no JVB JingleSession Logger.js:124:12
[JitsiConference.js] <X.prototype._doReplaceTrack>:  _doReplaceTrack - no P2P JingleSession Logger.js:124:12
[modules/remotecontrol/RemoteControl.js] <value>:  Initializing remote control. Logger.js:124
[modules/xmpp/moderator.js] <d.prototype.setFocusUserJid>:  Focus jid set to:  focus@auth.meet.jitsi Logger.js:124:12
[modules/xmpp/moderator.js] <d.prototype.createConferenceIq>:  Session ID: null machine UID: ad069798687e776bec8fadf09b86e980 Logger.js:124:12
[react/features/base/tracks/actions.js] <p/</</<>:  Replace audio track - unmuted Logger.js:124
[react/features/base/tracks/actions.js] <p/</</<>:  Replace video track - unmuted Logger.js:124
[conference.js] <updateAudioIconEnabled>:  Microphone button enabled: true local audio: LocalTrack[1,audio] audio devices:  device count: 0 Logger.js:124
[conference.js] <updateVideoIconEnabled>:  Camera button enabled: true local video: LocalTrack[2,video] video devices:  device count: 0
Logger.js:124
[react/features/local-recording/controller/RecordingController.js] <value>:  Switch microphone to Yadchw9RHBGIDgOfGbwys7ub712N/421vj3yEuMRtOQ= Logger.js:124
[conference.js] <updateAudioIconEnabled>:  Microphone button enabled: true local audio: LocalTrack[1,audio] audio devices: [object MediaDeviceInfo],[object MediaDeviceInfo],[object MediaDeviceInfo],[object MediaDeviceInfo] device count: 4 Logger.js:124
[conference.js] <updateVideoIconEnabled>:  Camera button enabled: true local video: LocalTrack[2,video] video devices: [object MediaDeviceInfo],[object MediaDeviceInfo] device count: 2 Logger.js:124
[modules/xmpp/moderator.js] <d.prototype.parseConfigOptions>:  Authentication enabled: false Logger.js:124:12
[modules/xmpp/moderator.js] <d.prototype.parseConfigOptions>:  External authentication enabled: false Logger.js:124:12
[modules/xmpp/moderator.js] <d.prototype.parseConfigOptions>:  Sip gateway enabled:  true Logger.js:124:12
[modules/xmpp/ChatRoom.js] <value>:  entered nidomeetsmyzel@muc.meet.jitsi/focus 
Object { affiliation: "owner", role: "moderator", jid: "focus@auth.meet.jitsi/focus21332463887086106", isFocus: true, isHiddenDomain: false }
Logger.js:124:12
[modules/xmpp/ChatRoom.js] <value>:  Ignore focus: nidomeetsmyzel@muc.meet.jitsi/focus, real JID: focus@auth.meet.jitsi/focus21332463887086106 Logger.js:124:12
[modules/version/ComponentsVersions.js] <o.prototype.processPresence/<>:  Got xmpp version: Prosody(0.11.2,Linux) Logger.js:124:12
[modules/version/ComponentsVersions.js] <o.prototype.processPresence/<>:  Got focus version: JiCoFo(1.0.1.0-457,Linux) Logger.js:124:12
[modules/xmpp/ChatRoom.js] <value>:  entered nidomeetsmyzel@muc.meet.jitsi/q2li_l9m 
Object { affiliation: "owner", role: "moderator", jid: "q2li_l9mpqactgrm@meet.jitsi/RLF8LfFd", isFocus: false, isHiddenDomain: false, nick: "Chris" }
Logger.js:124:12
[modules/UI/videolayout/RemoteVideo.js] <v.prototype.updateConnectionStatusIndicator>:  q2li_l9m thumbnail connection status: active
Logger.js:124
[conference.js] <_setupListeners/<>:  USER q2li_l9m connnected: 
Object { _jid: "nidomeetsmyzel@muc.meet.jitsi/q2li_l9m", _id: "q2li_l9m", _conference: {…}, _displayName: "Chris", _supportsDTMF: false, _tracks: [], _role: "moderator", _status: undefined, _hidden: false, _statsID: undefined, … }
Logger.js:124
[JitsiConference.js] <X.prototype._maybeStartOrStopP2P>:  Auto P2P disabled Logger.js:124:12
[conference.js] <_setupListeners/<>:  My role changed, new role: none Logger.js:124
[JitsiConference.js] <X.prototype._maybeStartOrStopP2P>:  Auto P2P disabled Logger.js:124:12
[modules/xmpp/ChatRoom.js] <value>:  (TIME) MUC joined:	 10954 Logger.js:124:12
[modules/xmpp/ChatRoom.js] <value>:  Subject is changed to Logger.js:124:12
[modules/UI/videolayout/LargeVideoManager.js] <value/<>:  hover in %s reznsoa8 Logger.js:124
[modules/xmpp/ChatRoom.js] <value>:  Ignore focus: nidomeetsmyzel@muc.meet.jitsi/focus, real JID: focus@auth.meet.jitsi/focus21332463887086106 Logger.js:124:12
[react/features/overlay/components/AbstractPageReloadOverlay.js] <value>:  The conference will be reloaded after 23 seconds. Logger.js:124
[modules/UI/videolayout/VideoLayout.js] <electLastVisibleVideo>:  electLastVisibleVideo: q2li_l9m Logger.js:124
[modules/UI/videolayout/VideoLayout.js] <removeParticipantContainer>:  Removing remote video: q2li_l9m Logger.js:124
[modules/UI/videolayout/SmallVideo.js] <_.prototype.remove>:  Remove thumbnail q2li_l9m Logger.js:124
[conference.js] <value>:  CONFERENCE FAILED: conference.videobridgeNotAvailable Logger.js:124
[modules/UI/videolayout/SmallVideo.js] <_.prototype.remove>:  Remove thumbnail reznsoa8 Logger.js:124
[modules/rttmonitor/rttmonitor.js] <value>:  Stopping RttMonitor. Logger.js:124:12
[modules/e2eping/e2eping.js] <value>:  Stopping e2eping Logger.js:124:12
[modules/xmpp/ChatRoom.js] <value>:  do leave nidomeetsmyzel@muc.meet.jitsi/reznsoa8 Logger.js:124:12
[modules/xmpp/strophe.jingle.js] <value>:  on jingle session-initiate from nidomeetsmyzel@muc.meet.jitsi/q2li_l9m 
<iq id="cmV6bnNvYThoajhmYmNjeUBt…xA4hrVawG9PlWTc9buh3g==" type="set" from="nidomeetsmyzel@muc.meet.jitsi/q2li_l9m" to="reznsoa8hj8fbccy@meet.jitsi/Z5Wwt3gZ" xmlns="jabber:client">
Logger.js:124:12
[modules/xmpp/strophe.jingle.js] <value>:  (TIME) received session-initiate:	 12558 Logger.js:124:12
[modules/xmpp/strophe.jingle.js] <value>:  Marking session from nidomeetsmyzel@muc.meet.jitsi/q2li_l9m as  P2P Logger.js:124:12
[modules/RTC/RTC.js] <value>:  Removed remote tracks for q2li_l9m count: 0 Logger.js:124:12
[modules/UI/videolayout/VideoLayout.js] <removeParticipantContainer>:  No remote video for q2li_l9m Logger.js:124
[conference.js] <_setupListeners/<>:  USER q2li_l9m LEFT: 
Object { _jid: "nidomeetsmyzel@muc.meet.jitsi/q2li_l9m", _id: "q2li_l9m", _conference: {…}, _displayName: "Chris", _supportsDTMF: false, _tracks: [], _role: "moderator", _status: undefined, _hidden: false, _statsID: undefined, … }
Logger.js:124
[JitsiConference.js] <X.prototype._maybeStartOrStopP2P>:  Auto P2P disabled Logger.js:124:12
[modules/xmpp/moderator.js] <d.prototype.onMucMemberLeft>:  Someone left is it focus ? nidomeetsmyzel@muc.meet.jitsi/q2li_l9m Logger.js:124:12
[conference.js] <_setupListeners/<>:  My role changed, new role: moderator Logger.js:124
[JitsiMeetJS.js] <getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: "Strophe: showModeratorIndicator@https://meet.oi.myzel.io/libs/app.bundle.min.js?v=3216:16:10064
_.updateLocalRole@https://meet.oi.myzel.io/libs/app.bundle.min.js?v=3216:248:209187
_setupListeners/<@https://meet.oi.myzel.io/libs/app.bundle.min.js?v=3216:248:173540
r.prototype.emit@https://meet.oi.myzel.io/libs/lib-jitsi-meet.min.js?v=3216:6:152389
X.prototype.onLocalRoleChanged@https://meet.oi.myzel.io/libs/lib-jitsi-meet.min.js?v=3216:6:293309
b.prototype.setupChatRoomListeners/<@https://meet.oi.myzel.io/libs/lib-jitsi-meet.min.js?v=3216:6:328708
r.prototype.emit@https://meet.oi.myzel.io/libs/lib-jitsi-meet.min.js?v=3216:6:152350
value@https://meet.oi.myzel.io/libs/lib-jitsi-meet.min.js?v=3216:25:65699
value@https://meet.oi.myzel.io/libs/lib-jitsi-meet.min.js?v=3216:25:58413
run@https://meet.oi.myzel.io/libs/lib-jitsi-meet.min.js?v=3216:6:21513
_dataRecv/<@https://meet.oi.myzel.io/libs/lib-jitsi-meet.min.js?v=3216:6:29833
forEachChild@https://meet.oi.myzel.io/libs/lib-jitsi-meet.min.js?v=3216:6:13288
_dataRecv@https://meet.oi.myzel.io/libs/lib-jitsi-meet.min.js?v=3216:6:29666
_onRequestStateChange@https://meet.oi.myzel.io/libs/lib-jitsi-meet.min.js?v=3216:6:49165
"
    log strophe.util.js:89
    fatal strophe.js:2093
    _handleError strophe.js:1995
    run strophe.js:2558
    _dataRecv strophe.js:3822
    forEachChild strophe.js:1522
    _dataRecv strophe.js:3810
    _onRequestStateChange strophe.js:5559
Logger.js:124:12
[modules/xmpp/strophe.util.js] <t.a/i.Strophe.log>:  Strophe: showModeratorIndicator@https://meet.oi.myzel.io/libs/app.bundle.min.js?v=3216:16:10064
_.updateLocalRole@https://meet.oi.myzel.io/libs/app.bundle.min.js?v=3216:248:209187
_setupListeners/<@https://meet.oi.myzel.io/libs/app.bundle.min.js?v=3216:248:173540
r.prototype.emit@https://meet.oi.myzel.io/libs/lib-jitsi-meet.min.js?v=3216:6:152389
X.prototype.onLocalRoleChanged@https://meet.oi.myzel.io/libs/lib-jitsi-meet.min.js?v=3216:6:293309
b.prototype.setupChatRoomListeners/<@https://meet.oi.myzel.io/libs/lib-jitsi-meet.min.js?v=3216:6:328708
r.prototype.emit@https://meet.oi.myzel.io/libs/lib-jitsi-meet.min.js?v=3216:6:152350
value@https://meet.oi.myzel.io/libs/lib-jitsi-meet.min.js?v=3216:25:65699
value@https://meet.oi.myzel.io/libs/lib-jitsi-meet.min.js?v=3216:25:58413
run@https://meet.oi.myzel.io/libs/lib-jitsi-meet.min.js?v=3216:6:21513
_dataRecv/<@https://meet.oi.myzel.io/libs/lib-jitsi-meet.min.js?v=3216:6:29833
forEachChild@https://meet.oi.myzel.io/libs/lib-jitsi-meet.min.js?v=3216:6:13288
_dataRecv@https://meet.oi.myzel.io/libs/lib-jitsi-meet.min.js?v=3216:6:29666
_onRequestStateChange@https://meet.oi.myzel.io/libs/lib-jitsi-meet.min.js?v=3216:6:49165
Logger.js:124:12
[JitsiMeetJS.js] <getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: "Strophe: error: undefined https://meet.oi.myzel.io/libs/app.bundle.min.js?v=3216:16 - TypeError: w is null"
    log strophe.util.js:89
    fatal strophe.js:2093
    _handleError strophe.js:2001
    run strophe.js:2558
    _dataRecv strophe.js:3822

```
