### ISSUE TITLE
All and only necessary debconf answers/questions for jitsi-meet?

### ISSUE THREAD

**Issue by fooness** [jitsi/jitsi-meet#7879]
_As there’s unfortunately no official ansible playbook …_

Could anyone please share all necessary(!) debconf questions and answers jitsi-meet would need when being installed automatically, e.g. via ansible? I’ve read through the docs, issues, and some ansible playbooks … but every source defines different questions/answer.

– https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-scalable
– https://github.com/tderflinger/jitsi-deployment/blob/master/ansible/install_jitsi.yml
– https://github.com/systemli/ansible-role-jitsi-meet/blob/master/tasks/jitsi-meet.yml

Here’s the part of my ansible playbook which I’d like to streamline and to tidy up:

```
jitsi_meet_debconf_options:
  #- name: jitsi-meet-web-config
  #  question: jitsi-meet/jvb-hostname
  #  value: "{{ jitsi_meet_server_name }}"
  #  vtype: string
  #- name: jitsi-meet-web-config
  #  question: jitsi-videobridge/jvb-hostname
  #  value: "{{ jitsi_meet_server_name }}"
  #  vtype: string
  #
  #- name: jicofo
  #  question: jitsi-videobridge/jvb-hostname
  #  value: "{{ jitsi_meet_server_name }}"
  #  vtype: string
  #
  - name: jitsi-meet-web-config
    question: jitsi-meet/cert-choice
    value: "{{ jitsi_meet_cert_choice }}"
    vtype: select
  - name: jitsi-meet-web-config
    question: jitsi-meet/cert-path-crt
    value: "{{ jitsi_meet_cert_path_crt }}"
    vtype: string
  - name: jitsi-meet-web-config
    question: jitsi-meet/cert-path-key
    value: "{{ jitsi_meet_cert_path_key }}"
    vtype: string
  #
  #- name: jitsi-meet-prosody
  #  question: jitsi-meet-prosody/jvb-hostname
  #  value: "{{ jitsi_meet_server_name }}"
  #  vtype: string
  - name: jitsi-meet-prosody
    question: jitsi-videobridge/jvb-hostname
    value: "{{ jitsi_meet_server_name }}"
    vtype: string
  #- name: jitsi-meet-prosody
  #  question: jitsi-meet-prosody/turn-secret
  #  value: "{{ jitsi_meet_turn_secret }}"
  #  vtype: string
  #
  - name: jitsi-videobridge
    question: jitsi-videobridge/jvb-hostname
    value: "{{ jitsi_meet_server_name }}"
    vtype: string
```

Thank you very much!
